export declare const env: {
    PORT: number;
    DEV_PORT: number;
    CLIENT_PORT: number;
    CLIENT_DEV_PORT: number;
    GITHUB_OAUTH_TOKEN: string;
    ACCESS_TOKEN_SECRET: string;
    REFRESH_TOKEN_SECRET: string;
    ACCESS_TOKEN_LIFETIME: string;
    PUSH_API_URL: string;
    TEST_EXPO_PUSH_TOKEN: string;
    MAIL_SERVICE: string;
    MAIL_HOST: string;
    MAIL_PORT: number;
    MAIL_USERNAME: string;
    MAIL_PASSWORD: string;
    CAU_ID: string;
    CAU_PW: string;
    TIME_ZONE: string;
    IMGUR_HOST: string;
    IMGUR_CLIENT_ID: string;
    TELEGRAM_BOT_TOKEN: string;
};
