/**
 * Copyright 2020 jhaemin
 *
 * Refresh One API Schemas & Functions
 *
 * This file is automatically generated
 * by the script "refresh".
 * Do not modify this file manually.
 * If there comes a situation where this file
 * should move to other place,
 * please update the source "dev/refresh.js".
 */

import { Action as AddDeviceRaw } from './device/add-device.action/interface'
import { Action as CreateTipRaw } from './tip/create-tip.action/interface'
import { Action as DeleteCommentRaw } from './square/delete-comment.action/interface'
import { Action as DeletePostRaw } from './square/delete-post.action/interface'
import { Action as EditPostRaw } from './square/edit-post.action/interface'
import { Action as GetBoardIdRaw } from './square/get-board-id.action/interface'
import { Action as GetCommentsRaw } from './square/get-comments.action/interface'
import { Action as GetDevicesRaw } from './device/get-devices.action/interface'
import { Action as GetMyPostsRaw } from './my/get-my-posts.action/interface'
import { Action as GetMySubscriptionsRaw } from './notice/get-my-subscriptions.action/interface'
import { Action as GetNoticeCatalogRaw } from './notice/get-notice-catalog.action/interface'
import { GetPostById } from './square/get-post-by-id'
import { Action as GetPostLikesRaw } from './square/like/get-post-likes.action/interface'
import { Action as GetPostsOfBoardRaw } from './square/get-posts-of-board.action/interface'
import { Action as GetRecentPostsOfBoardRaw } from './square/get-recent-posts-of-board.action/interface'
import { Action as GetTipRaw } from './tip/get-tip-detail.action/interface'
import { Action as GetTipTopicRaw } from './tip/get-topics.action/interface'
import { Action as GetUserIdRaw } from './auth/get-user-id.action/interface'
import { Action as IsPostLikedRaw } from './square/like/is-post-liked.action/interface'
import { Action as LikePostRaw } from './square/like/like-post.action/interface'
import { Action as SavePostRaw } from './square/save-post.action/interface'
import { Action as UpdateNoticeSubscriptionRaw } from './notice/update-notice-subscription.action/interface'
import { Action as UploadCommentRaw } from './square/upload-comment.action/interface'
import { UploadPost } from './square/upload-post'
export { GetPostById } from './square/get-post-by-id'
export { UploadPost } from './square/upload-post'
export type GetUserId = GetUserIdRaw & { action: 'getUserId' }

export type AddDevice = AddDeviceRaw & { action: 'addDevice' }

export type GetDevices = GetDevicesRaw & { action: 'getDevices' }

export type GetMyPosts = GetMyPostsRaw & { action: 'getMyPosts' }

export type GetMySubscriptions = GetMySubscriptionsRaw & {
  action: 'getMySubscriptions'
}

export type GetNoticeCatalog = GetNoticeCatalogRaw & {
  action: 'getNoticeCatalog'
}

export type UpdateNoticeSubscription = UpdateNoticeSubscriptionRaw & {
  action: 'updateNoticeSubscription'
}

export type DeleteComment = DeleteCommentRaw & { action: 'deleteComment' }

export type DeletePost = DeletePostRaw & { action: 'deletePost' }

export type EditPost = EditPostRaw & { action: 'editPost' }

export type GetBoardId = GetBoardIdRaw & { action: 'getBoardId' }

export type GetComments = GetCommentsRaw & { action: 'getComments' }

export type GetPostsOfBoard = GetPostsOfBoardRaw & { action: 'getPostsOfBoard' }

export type GetRecentPostsOfBoard = GetRecentPostsOfBoardRaw & {
  action: 'getRecentPostsOfBoard'
}

export type GetPostLikes = GetPostLikesRaw & { action: 'getPostLikes' }

export type IsPostLiked = IsPostLikedRaw & { action: 'isPostLiked' }

export type LikePost = LikePostRaw & { action: 'likePost' }

export type SavePost = SavePostRaw & { action: 'savePost' }

export type UploadComment = UploadCommentRaw & { action: 'uploadComment' }

export type GetTipTopics = GetTipTopicRaw & {
  action: 'getTipTopics'
}

export type CreateTip = CreateTipRaw & { action: 'createTip' }
export type GetTip = GetTipRaw & { action: 'getTip' }

export type OneApiAction =
  | GetPostById
  | UploadPost
  | GetUserId
  | AddDevice
  | GetDevices
  | GetMyPosts
  | GetMySubscriptions
  | GetNoticeCatalog
  | UpdateNoticeSubscription
  | DeleteComment
  | DeletePost
  | EditPost
  | GetBoardId
  | GetComments
  | GetPostsOfBoard
  | GetRecentPostsOfBoard
  | GetPostLikes
  | IsPostLiked
  | LikePost
  | SavePost
  | UploadComment
  | GetTipTopics
  | CreateTip
  | GetTip
