/**
 * Copyright 2020 jhaemin
 *
 * Refresh One API Schemas & Functions
 *
 * This file is automatically generated
 * by the script "refresh".
 * Do not modify this file manually.
 * If there comes a situation where this file
 * should move to other place,
 * please update the source "dev/refresh.js".
 */

import { FetchRecentPostsOfBoard } from './square/fetch-recent-posts-of-board'
export { FetchRecentPostsOfBoard } from './square/fetch-recent-posts-of-board'
import { GetPostById } from './square/get-post-by-id'
export { GetPostById } from './square/get-post-by-id'
import { UploadPost } from './square/upload-post'
export { UploadPost } from './square/upload-post'
import { Action as GetUserIdRaw } from './auth/get-user-id.action/interface'
export type GetUserId = GetUserIdRaw & { action: 'getUserId' }

import { Action as GetMyPostsRaw } from './my/get-my-posts.action/interface'
export type GetMyPosts = GetMyPostsRaw & { action: 'getMyPosts' }

import { Action as DeleteCommentRaw } from './square/delete-comment.action/interface'
export type DeleteComment = DeleteCommentRaw & { action: 'deleteComment' }

import { Action as DeletePostRaw } from './square/delete-post.action/interface'
export type DeletePost = DeletePostRaw & { action: 'deletePost' }

import { Action as EditPostRaw } from './square/edit-post.action/interface'
export type EditPost = EditPostRaw & { action: 'editPost' }

import { Action as GetBoardIdRaw } from './square/get-board-id.action/interface'
export type GetBoardId = GetBoardIdRaw & { action: 'getBoardId' }

import { Action as GetCommentsRaw } from './square/get-comments.action/interface'
export type GetComments = GetCommentsRaw & { action: 'getComments' }

import { Action as GetPostsOfBoardRaw } from './square/get-posts-of-board.action/interface'
export type GetPostsOfBoard = GetPostsOfBoardRaw & { action: 'getPostsOfBoard' }

import { Action as GetPostLikesRaw } from './square/like/get-post-likes.action/interface'
export type GetPostLikes = GetPostLikesRaw & { action: 'getPostLikes' }

import { Action as IsPostLikedRaw } from './square/like/is-post-liked.action/interface'
export type IsPostLiked = IsPostLikedRaw & { action: 'isPostLiked' }

import { Action as LikePostRaw } from './square/like/like-post.action/interface'
export type LikePost = LikePostRaw & { action: 'likePost' }

import { Action as SavePostRaw } from './square/save-post.action/interface'
export type SavePost = SavePostRaw & { action: 'savePost' }

import { Action as UploadCommentRaw } from './square/upload-comment.action/interface'
export type UploadComment = UploadCommentRaw & { action: 'uploadComment' }

export type OneApiAction =
  | FetchRecentPostsOfBoard
  | GetPostById
  | UploadPost
  | GetUserId
  | GetMyPosts
  | DeleteComment
  | DeletePost
  | EditPost
  | GetBoardId
  | GetComments
  | GetPostsOfBoard
  | GetPostLikes
  | IsPostLiked
  | LikePost
  | SavePost
  | UploadComment
