/**
 * Copyright 2020 jhaemin
 *
 * Refresh One API Schemas & Functions
 *
 * This file is automatically generated
 * by the script "refresh".
 * Do not modify this file manually.
 * If there comes a situation where this file
 * should move to other place,
 * please update the source "dev/refresh.js".
 */

import { FetchPostsOfBoard } from './square/fetch-posts-of-board'
export { FetchPostsOfBoard } from './square/fetch-posts-of-board'
import { FetchRecentPostsOfBoard } from './square/fetch-recent-posts-of-board'
export { FetchRecentPostsOfBoard } from './square/fetch-recent-posts-of-board'
import { GetPostById } from './square/get-post-by-id'
export { GetPostById } from './square/get-post-by-id'
import { UploadPost } from './square/upload-post'
export { UploadPost } from './square/upload-post'
import { Interface as GetUserIdRaw } from './auth/get-user-id.action/interface'
export type GetUserId = GetUserIdRaw & { action: 'getUserId' }

import { Interface as DeleteCommentRaw } from './square/delete-comment.action/interface'
export type DeleteComment = DeleteCommentRaw & { action: 'deleteComment' }

import { Interface as DeletePostRaw } from './square/delete-post.action/interface'
export type DeletePost = DeletePostRaw & { action: 'deletePost' }

import { Interface as EditPostRaw } from './square/edit-post.action/interface'
export type EditPost = EditPostRaw & { action: 'editPost' }

import { Interface as GetBoardIdRaw } from './square/get-board-id.action/interface'
export type GetBoardId = GetBoardIdRaw & { action: 'getBoardId' }

import { Interface as GetCommentsRaw } from './square/get-comments.action/interface'
export type GetComments = GetCommentsRaw & { action: 'getComments' }

import { Interface as SavePostRaw } from './square/save-post.action/interface'
export type SavePost = SavePostRaw & { action: 'savePost' }

import { Interface as UploadCommentRaw } from './square/upload-comment.action/interface'
export type UploadComment = UploadCommentRaw & { action: 'uploadComment' }

export type APIScheme =
  | FetchPostsOfBoard
  | FetchRecentPostsOfBoard
  | GetPostById
  | UploadPost
  | GetUserId
  | DeleteComment
  | DeletePost
  | EditPost
  | GetBoardId
  | GetComments
  | SavePost
  | UploadComment
