/**
 * Copyright 2020 jhaemin
 *
 * Refresh One API Schemas & Functions
 *
 * This file is automatically generated
 * by the script "refresh".
 * Do not modify this file manually.
 * If there comes a situation where this file
 * should move to other place,
 * please update the source "dev/refresh.js".
 */

export { fetchCommentsOfPost } from './square/fetch-comments-of-post.f'
export { fetchPostsOfBoard } from './square/fetch-posts-of-board.f'
export { fetchRecentPostsOfBoard } from './square/fetch-recent-posts-of-board.f'
export { getPostById } from './square/get-post-by-id.f'
export { uploadPost } from './square/upload-post.f'
