import dayjs from 'dayjs';
declare const _default: {
    PORT: number;
    DEV_PORT: number;
    PUSH_API_URL: string;
    TEST_EXPO_PUSH_TOKEN: string;
    DB_HOST: string;
    DB_USER: string;
    DB_PASSWORD: string;
    DB_NAME: string;
    DB_NAME_DEV: string;
    MAIL_SERVICE: string;
    MAIL_HOST: string;
    MAIL_PORT: number;
    MAIL_USERNAME: string;
    MAIL_PASSWORD: string;
    ACCESS_TOKEN_SECRET: string;
    REFRESH_TOKEN_SECRET: string;
    ACCESS_TOKEN_EXPIRE: string;
    REFRESH_TOKEN_EXPIRE: string;
    REFRESH_TOKEN_REFRESH_ALLOWED_VALUE: number;
    REFRESH_TOKEN_REFRESH_ALLOWED_UNIT: dayjs.UnitType;
    CAU_ID: string;
    CAU_PW: string;
    STORAGE_PATH: string;
    STORAGE_PATH_DEV: string;
    TIME_ZONE: string;
    CDN_PORT: number;
    CDN_DEV_PORT: number;
    PUBLIC_DIR: string;
};
export default _default;
